# Configuration file for prompting

train:
  model_name: "google/vit-base-patch16-224-in21k"
  project_name: "cnn_wildfire_households"
  path_to_data: "data/images_examples"
  epochs: 20
  output_dir: "results"
  resume_from_checkpoint: False
  batch_size_train: 16
  batch_size_test: 16
  warmup_steps: 500
  learning_rate: 0.1
  weight_decay: 0.01
  dropout_attention: 0.2,
  dropout_hidden: 0.2
