# Configuration file for prompting

train:
  model_name: "roberta-base"
  path_to_train: "/home/topcat/projects/cs231n_project/data/cleaned_images/train"
  path_to_test: "/home/topcat/projects/cs231n_project/data/cleaned_images/test"
  tabular_data_path: /mnt/sherlock/oak/cnn_fire_fuel/cleaned_homes/augmented_dataset.csv 
  output_dir: "./results_roberta"
  resume_from_checkpoint: False
  epochs: 10
  learning_rate: 5e-5
  batch_size_train: 32
  batch_size_test: 32
  warmup_steps: 500
  weight_decay: 0.01

prompts:
  label_column: destroyed
  id_var: homeid
  add_response: False
  prompt_type: template
  columns_of_interest:
    - yearbuilt 
    - aspect
    - elev
    - slope_r25
    - age
    - riskToStru
    - firename
    - homeid
    - destroyed

  column_name_map:
    yearbuilt: Year Built,
    elev: Elevation,
    slope_r25: Slope,
    aspect: Aspect,
    age: Age,
    firename: Fire Name,
    riskToStru: Risk to structure

  template: >
    This house is {} years old. It is located {} meters above sea level with a
    slope of {}. The risk to structure is {}. The fire name is {}
  cols_template:
    - age
    - elev
    - slope_r25
    - riskToStru
    - firename

  final_prompt: ""
  #final_prompt: "Is this house going to be destroyed? Yes or no? Answer:"
