# Configuration file for prompting

train:
  model_name: "google/vit-base-patch16-224-in21k"
  path_to_data: "data/images"
  tabular_data_path: "/mnt/sherlock/oak/mburke/cnn_fire_fuel/cleaned_homes/augmented_dataset.csv"
  epochs: 20
  output_dir: "results"
  resume_from_checkpoint: False
  batch_size_train: 16
  batch_size_test: 16
  warmup_steps: 500
  learning_rate: 0.1
  weight_decay: 0.01

