# Configuration file for prompting

train:
  model_name: "google/vit-base-patch16-224"
  #model_name: "google/vit-base-patch16-224-in21k"
  #model_name:  "google/vit-base-patch16-224"
  path_to_train: "/oak/stanford/schools/ees/mburke/cnn_fire_fuel/data/train"
  path_to_test: "/oak/stanford/schools/ees/mburke/cnn_fire_fuel/data/test"
  tabular_data_path: "/oak/stanford/schools/ees/mburke/cnn_fire_fuel/cleaned_homes/augmented_dataset.csv"
  output_dir: "/scratch/users/ihigueme/results_vit_new"
  resume_from_checkpoint: False
  epochs: 10
  warmup_steps: 500
  learning_rate: 0.01
  batch_size_train: 64
  batch_size_test: 64
  weight_decay: 0.1
  dropout_hidden: 0.5
  dropout_attention: 0.5
  
